name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > key.json || echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > key.json
          
          if [ -s key.json ]; then
            echo "key.json file created successfully."
          else
            echo "key.json is empty."
            exit 1
          fi
        
          gcloud auth activate-service-account --key-file=key.json

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-app/flask-app:latest .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-app/flask-app:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy flask-app \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-app/flask-app:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }},FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }},FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }},FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }},FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }},FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }},FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }},FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Clean up credentials
        run: rm -f key.json
